- name: Create Phabricator directory
  file:
    path: "{{ installation_directory }}"
    state: directory

- name: Download git Arcanist repositories
  git:
    repo: "{{ item.value }}"
    dest: "{{ installation_directory }}/{{ item.key }}"
    accept_hostkey: yes
  with_dict: "{{ phabricator_repositories }}"

- name: Add arc to users' PATH - user version
  lineinfile:
    dest: "~/.bashrc"
    line: "export PATH=\"$PATH:{{ installation_directory }}/arcanist/bin/\""
  become: true
  become_user: vagrant

- name: Add arc to users' PATH - shell version
  lineinfile:
    dest: "~/.bash_profile"
    line: "export PATH=\"$PATH:{{ installation_directory }}/arcanist/bin/\""
  become: true
  become_user: vagrant

- name: Copy Arcanist configuration file
  template:
    src: ".arcrc.j2"
    dest: "/home/vagrant/.arcrc"
    owner: vagrant
    group: vagrant
    mode: 0600
